pipeline {
  agent { label 'entel' }

  environment {
    AWS_REGION = "us-east-1"
    TF_DIR = "iac"

    AWS_CREDENTIALS = credentials('aws-credentials')
    AWS_SESSION_TOKEN = credentials('aws-session-token')
  }

  stages {
    stage('Checkout') {
      steps {
        git url: 'https://github.com/Organization-vash/infraestructure.git', branch: 'feature/jenkins'
      }
    }

    stage('Build Java Lambdas') {
      steps {
        dir('lambda_agency') {
          sh 'mvn clean package'
        }
        dir('lambda_code') {
          sh 'mvn clean package'
        }
        dir('lambda_modules') {
          sh 'mvn clean package'
        }
        dir('lambda_services') {
          sh 'mvn clean package'
        }
        dir('lambda_users') {
          sh 'mvn clean package'
        }
      }
    }

    stage('Terraform Init & Apply') {
      steps {
        dir("${env.TF_DIR}") {
          sh '''
            export AWS_ACCESS_KEY_ID=${AWS_CREDENTIALS_USR}
            export AWS_SECRET_ACCESS_KEY=${AWS_CREDENTIALS_PSW}
            export AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN}
            terraform init
            terraform apply -auto-approve
          '''
        }
      }

      post {
        failure {
          echo '💥 terraform apply falló. Ejecutando terraform destroy automáticamente...'
          dir("${env.TF_DIR}") {
            sh '''
              export AWS_ACCESS_KEY_ID=${AWS_CREDENTIALS_USR}
              export AWS_SECRET_ACCESS_KEY=${AWS_CREDENTIALS_PSW}
              export AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN}
              terraform destroy -auto-approve
            '''
          }
        }
      }
    }

    stage('Update Angular Environment') {
      steps {
        script {
          def apiUrl = sh(
            script: "terraform -chdir=${env.TF_DIR} output -raw api_gateway_url",
            returnStdout: true
          ).trim()

          sh """
            sed -i 's|baseURL:.*|baseURL: "${apiUrl}"|g' iac/front/src/app/assets/environment.ts
          """
        }
      }

      post {
        failure {
          echo '💥 La inyencción de la nueva URL falló. Ejecutando terraform destroy automáticamente...'
          dir("${env.TF_DIR}") {
            sh '''
              export AWS_ACCESS_KEY_ID=${AWS_CREDENTIALS_USR}
              export AWS_SECRET_ACCESS_KEY=${AWS_CREDENTIALS_PSW}
              export AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN}
              terraform destroy -auto-approve
            '''
          }
        }
      }
    }

    stage('Build Frontend & Deploy') {
      steps {
        dir('iac/front') {
          sh 'npm install'
          sh 'npm run build -- --configuration production --project gestion-servicio-frontend'
          sh '''
            export AWS_ACCESS_KEY_ID=${AWS_CREDENTIALS_USR}
            export AWS_SECRET_ACCESS_KEY=${AWS_CREDENTIALS_PSW}
            export AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN}
            aws s3 sync ./dist/gestion-servicio-frontend/browser/ s3://entel-s3-bucket-21 --delete
          '''
        }
      }
    }

    stage('Destroy Infra') {
      steps {
        echo '⏳ Esperando 10 minutos antes de destruir la infraestructura...'
        sleep time: 10, unit: 'MINUTES'
        dir("${env.TF_DIR}") {
          sh '''
            export AWS_ACCESS_KEY_ID=${AWS_CREDENTIALS_USR}
            export AWS_SECRET_ACCESS_KEY=${AWS_CREDENTIALS_PSW}
            export AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN}
            terraform destroy -auto-approve
          '''
        }
      }
    }
  }
}
